fix: cd

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -21,13 +21,30 @@ jobs:
           key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
           port: ${{ secrets.VPS_PORT }}
           script: |
+            # Ensure Node.js and npm are installed
+            if ! command -v node &> /dev/null || ! command -v npm &> /dev/null
+            then
+              echo "Node.js or npm not found. Installing Node.js..."
+              sudo apt update
+              sudo apt install -y nodejs npm
+            else
+              echo "Node.js and npm are already installed."
+            fi
+
+            # Check if the directory fe-hero_pos exists
             if [ -d "fe-hero_pos" ]; then
+              echo "Directory fe-hero_pos exists, pulling the latest changes..."
               cd fe-hero_pos || exit
               git pull origin main
             else
+              echo "Directory fe-hero_pos not found, cloning repository..."
               git clone https://github.com/IJ4L/fe-hero_pos
               cd fe-hero_pos || exit
             fi
 
-            sudo npm i
-            sudo npm run build
+            # Install dependencies and build the project
+            echo "Installing dependencies..."
+            npm install
+
+            echo "Building the project..."
+            npm run build
